version: "3.8"
services:
  squid01:
    container_name: "squid01"
    image: ubuntu/squid
    ports:
      - 13128:3128
    volumes:
      - ./squid01/squid.conf:/etc/squid/squid.conf
      - ./squid01/log:/var/log/squid
      - ./squid01/whitelist:/etc/squid/whitelist
    networks:
      web_segment:
        ipv4_address: 192.168.1.2
  squid02:
    container_name: "squid02"
    image: ubuntu/squid
    ports:
      - 23128:3128
    volumes:
      - ./squid02/squid.conf:/etc/squid/squid.conf
      - ./squid02/log:/var/log/squid
      - ./squid02/whitelist:/etc/squid/whitelist
    networks:
      web_segment:
        ipv4_address: 192.168.1.3
  host:
    image: nginx:latest
    networks:
      web_segment:
        ipv4_address: 192.168.1.4
    volumes:
      - ./host/log:/var/log/nginx
      - ./host/nginx.conf:/etc/nginx/nginx.conf
networks:
  web_segment:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
